# ----------------------------------------
# Imports
# ----------------------------------------

from app.services.file_manifest.extractors.helper.constants import (
    COMMON_SKILLS,
    COMPANY_KEYWORDS,
    DATEPARSER_SETTINGS,
    DEFAULT_SECTION_KEYWORDS,
    DEFAULT_SKILL_SIMILARITY_THRESHOLD,
    FIELD_CLEAN_STRIP_CHARS,
    HANGING_CONTINUATION_WORDS,
    INCOMPATIBLE_SKILL_PAIRS,
    KEYWORDS_DATA,
    KNOWN_LANGUAGES,
    KNOWN_LOCATIONS,
    KNOWN_TOOLS,
    NON_SKILL_WORDS,
    PROJECT_FOOTER_KEYWORDS,
    ROLE_KEYWORDS,
    VALID_SINGLE_LETTER_SKILLS,
)
from app.services.file_manifest.extractors.helper.data_structures import (
    CaseInsensitiveList,
    EntityExtractionResult,
)
from app.services.file_manifest.extractors.helper.layout import (
    classify_drawing_shape,
    dumps_clean_layout_json,
    format_box,
    format_coordinate_value,
    format_font_descriptor,
    int_color_to_hex,
    normalize_page_size,
    rgb_tuple_to_hex,
    shorten_hex_color,
)
from app.services.file_manifest.extractors.helper.loaders import (
    DATA_DIR,
    load_canonical_skills,
    load_resume_keywords,
    load_section_headers,
)
from app.services.file_manifest.extractors.helper.parsers import (
    build_candidate_links,
    extract_entities_from_tables,
    infer_candidate_name_from_file_path,
    infer_role_from_file_path,
    split_role_and_company,
)
from app.services.file_manifest.extractors.helper.regex import (
    ANNOTATIONS_PATTERN,
    BRACKETED_PATTERN,
    BULLET_PATTERN,
    CAMEL_CASE_PATTERN,
    CGPA_PATTERN,
    CONSECUTIVE_NEWLINES_PATTERN,
    CURRENT_DATE_KEYWORDS_PATTERN,
    DATE_END_PREFIXES_PATTERN,
    DATE_PATTERN,
    DATE_RANGE_PATTERN,
    DATE_START_PREFIXES_PATTERN,
    DATE_YEAR_PATTERN,
    DEGREE_REGEXES,
    EMAIL_PATTERN,
    FOUR_DIGIT_YEAR_PATTERN,
    GITHUB_PATTERN,
    GLUED_MONTH_YEAR_PATTERN,
    GRADUATION_YEAR_PATTERN,
    HORIZONTAL_WHITESPACE_PATTERN,
    HTML_TAGS_PATTERN,
    HYPHENATION_PATTERN,
    INLINE_HEADER_PATTERN,
    INSTITUTION_REGEXES,
    JUNK_PATTERNS,
    LANGUAGES_HEADER_PATTERN,
    LINKEDIN_PATTERN,
    NAME_PREFIX_PATTERN,
    NON_PRINTABLE_PATTERN,
    PHONE_PATTERN,
    RECRUITER_SPLIT_PATTERN,
    SEPARATOR_PATTERN,
    SEPARATORS_PATTERN,
    SKILL_NORMALIZE_SEPARATOR_PATTERN,
    SMART_QUOTES_DASHES_PATTERNS,
    STANDALONE_PAGE_PATTERN,
    TRAILING_PAGE_PATTERN,
    URL_PATTERN,
)
from app.services.file_manifest.extractors.helper.validators import (
    is_degree_string,
    is_institution_string,
    is_location,
    is_valid_skill,
)


# ----------------------------------------
# Public Exports
# ----------------------------------------

__all__ = [
    "DATA_DIR",
    "load_section_headers",
    "load_resume_keywords",
    "load_canonical_skills",
    "KEYWORDS_DATA",
    "KNOWN_LOCATIONS",
    "ROLE_KEYWORDS",
    "COMPANY_KEYWORDS",
    "COMMON_SKILLS",
    "NON_SKILL_WORDS",
    "PROJECT_FOOTER_KEYWORDS",
    "DEFAULT_SECTION_KEYWORDS",
    "HANGING_CONTINUATION_WORDS",
    "FIELD_CLEAN_STRIP_CHARS",
    "DATEPARSER_SETTINGS",
    "DEFAULT_SKILL_SIMILARITY_THRESHOLD",
    "VALID_SINGLE_LETTER_SKILLS",
    "INCOMPATIBLE_SKILL_PAIRS",
    "CaseInsensitiveList",
    "EntityExtractionResult",
    "KNOWN_LANGUAGES",
    "KNOWN_TOOLS",
    "is_degree_string",
    "is_institution_string",
    "is_location",
    "is_valid_skill",
    "build_candidate_links",
    "split_role_and_company",
    "infer_candidate_name_from_file_path",
    "infer_role_from_file_path",
    "extract_entities_from_tables",
    "EMAIL_PATTERN",
    "PHONE_PATTERN",
    "URL_PATTERN",
    "LINKEDIN_PATTERN",
    "GITHUB_PATTERN",
    "DATE_PATTERN",
    "GRADUATION_YEAR_PATTERN",
    "CGPA_PATTERN",
    "DEGREE_REGEXES",
    "INSTITUTION_REGEXES",
    "SEPARATOR_PATTERN",
    "INLINE_HEADER_PATTERN",
    "LANGUAGES_HEADER_PATTERN",
    "JUNK_PATTERNS",
    "NAME_PREFIX_PATTERN",
    "RECRUITER_SPLIT_PATTERN",
    "BRACKETED_PATTERN",
    "SEPARATORS_PATTERN",
    "CAMEL_CASE_PATTERN",
    "ANNOTATIONS_PATTERN",
    "NON_PRINTABLE_PATTERN",
    "BULLET_PATTERN",
    "SMART_QUOTES_DASHES_PATTERNS",
    "STANDALONE_PAGE_PATTERN",
    "TRAILING_PAGE_PATTERN",
    "HYPHENATION_PATTERN",
    "HORIZONTAL_WHITESPACE_PATTERN",
    "CONSECUTIVE_NEWLINES_PATTERN",
    "HTML_TAGS_PATTERN",
    "DATE_YEAR_PATTERN",
    "DATE_RANGE_PATTERN",
    "CURRENT_DATE_KEYWORDS_PATTERN",
    "DATE_START_PREFIXES_PATTERN",
    "DATE_END_PREFIXES_PATTERN",
    "GLUED_MONTH_YEAR_PATTERN",
    "FOUR_DIGIT_YEAR_PATTERN",
    "SKILL_NORMALIZE_SEPARATOR_PATTERN",
    "int_color_to_hex",
    "rgb_tuple_to_hex",
    "shorten_hex_color",
    "format_coordinate_value",
    "format_box",
    "normalize_page_size",
    "classify_drawing_shape",
    "format_font_descriptor",
    "dumps_clean_layout_json",
]
